### ISSUE TITLE
URL specified in the request does not match the reply URLs configured in the application

### ISSUE THREAD

**Issue by waydaws** [ANSSI-FR/DFIR-O365RC#2]
Wen running search-o365, I get the following error.  Any ideas?

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'a0c73c16-a7e3-4564-9a95-2bdf47383716'.

**Comment by ldap389** [comment]
Hello waydaws,

To help troubleshoot the problem, can you please provide the following information?

- What version of PowerShell are you using? Is it a core edition?
- You have the problem with a particular parameter of the search-o365 function (FreeText, IPAddresses, UserIds) ? All of them? If you could tell me the exact command you are launching that would be great?
- Can you run the following command, and tell me if you have the same error message?
` Get-OAuthToken -Service EXO -silent:$false`
- Can you run your search and use the device code login and tell me if it works, here is an example:
`Search-O365 -StartDate $startdate -Enddate $enddate -FreeText "XXX" -DeviceCode:$true`

Thanks for you feedback

**Comment by ldap389** [comment]
Hello @waydaws ,

Do you have the problem with the latest version?
We thought we already fixed the problem with this commit:
https://github.com/ANSSI-FR/DFIR-O365RC/commit/eebb0fb9bb95c1557299c8043cd903480dd002c2
As it was announced by Microsoft as a breaking change:
https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-app-registration#redirect-uris

**Comment by ldap389** [comment]
Hello @waydaws ,
I will close the issue in a couple of days if I have no feedback
Regards

**Comment by ldap389** [comment]
No feedback, closing the issue
