### ISSUE TITLE
Set-PSRepository: No repository with the name 'PSGallery" was found

### ISSUE THREAD

**Issue by RenaudFrere** [ANSSI-FR/DFIR-O365RC#4]
Hello,

I wanted to give DFIR-O365RC a try but when I tried running it with Docker I got the following error:

Set-PSRepository: No repository with the name 'PSGallery" was found

![image](https://user-images.githubusercontent.com/90250126/161918864-91eba53e-222e-45f7-941b-fbe0367abf72.png)

I installed powershell on my Tsurugi workstation (Ubuntu 20.04) and run the following commang manually without any error.

pwsh -command Set-PSRepository PSGallery -InstallationPolicy Trusted

![image](https://user-images.githubusercontent.com/90250126/161919437-da8dfc1f-c075-4dbf-a46a-2d3d60e0ee7d.png)

Do you have an idea on what might be the issue here?

Thanks !

**Comment by RenaudFrere** [comment]
A reboot did the trick apparently.

**Comment by ldap389** [comment]
Hello,

OK, glad it works.
